[server]
headless = true
port = 8501
enableCORS = false

[theme]
base = "light"
primaryColor = "#0E7490"
backgroundColor = "#F8FAFC"
secondaryBackgroundColor = "#E2E8F0"
textColor = "#0F172A"
font = "sans serif"
